/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class GasolineCalculationGUI extends javax.swing.JFrame {

    /**
     * Creates new form GasolineCalculationGUI
     */
    public GasolineCalculationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        signgas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btndiesel = new javax.swing.JButton();
        btnbenzin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresult1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cbxgas2 = new javax.swing.JComboBox<>();
        cbxgas = new javax.swing.JComboBox<>();
        txtbenzin = new javax.swing.JTextField();
        txtdiesel = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtresult2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        signdiesel = new javax.swing.JComboBox<>();
        btnExit = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("รถเก๋ง :");

        signgas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasohol95", "Gasohol91", "Benzin91" }));
        signgas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signgasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("รถกระบะ :");

        btndiesel.setText("เติม");
        btndiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndieselActionPerformed(evt);
            }
        });

        btnbenzin.setText("เติม");
        btnbenzin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbenzinActionPerformed(evt);
            }
        });

        txtresult1.setColumns(20);
        txtresult1.setRows(5);
        jScrollPane1.setViewportView(txtresult1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("เลือกปั๊มน้ำมัน");

        cbxgas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PTT", "BCP", "Shell", "Esso" }));

        cbxgas.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        cbxgas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PTT", "BCP", "Shell", "Esso" }));

        txtbenzin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbenzinActionPerformed(evt);
            }
        });

        txtresult2.setColumns(20);
        txtresult2.setRows(5);
        jScrollPane2.setViewportView(txtresult2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("ราคา");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gasoline Calculation : โปรแกรมเติมนํ้ามันรถ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ใบเสร็จ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("คำนวณ ภาษี Vat /%");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        signdiesel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DieselB7", "DieselPremium" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signgas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(signdiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbenzin)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btndiesel)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel3)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxgas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(txtdiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxgas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtbenzin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6)))
                .addGap(0, 123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbenzin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxgas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signgas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbenzin))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxgas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndiesel)
                            .addComponent(signdiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbenzinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbenzinActionPerformed
        // TODO add your handling code her
        String msg,msg1,msg2,vatmsg = null;
        float gas91 = 0, gas95 = 0,ben91 = 0 ,result = 0, result1 = 0, result2 = 0;
        float Amount= 0,vat = 0;
        Float.parseFloat(txtbenzin.getText());
        
        String sign = (String) signgas.getSelectedItem();
        String sign1 = (String) cbxgas.getSelectedItem();
        
        if (sign.equals("Gasohol95") && sign1.equals("PTT")) {
            gas95 = Float.parseFloat(txtbenzin.getText());
            result = (float) (gas95 / 36.50);
            Amount = (float) (gas95/1.07);
            vat = (float) (Amount*7)/100;
            
            msg = "Gasoline PTT (Receipt) Gasohol95  "+"\n"+"="+result+"litre"+"  ราคา  "+gas95+"บาท"+"\n";
            vatmsg = "Gasoline PTT Tax Invoice Gasohol 95 "+"\n"+result+"litre"+"  ราคา  "+gas95+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gas95+" Bath "+"\n";
                    
            txtresult1.setText(String.valueOf(msg));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
            //JOptionPane.showMessageDialog(null, "กรุณาเลือกปั๊มPTT :");
        }
          
        if (sign.equals("Gasohol91") && sign1.equals("PTT")){
            gas91 = Float.parseFloat(txtbenzin.getText());
            result1 = (float) (gas91 / 33.24);
            Amount = (float) (gas91 / 1.07);
            vat = (float) (Amount*7)/100;
            
            msg1 = "Gasoline PTT (Receipt) Gasohol91  "+"\n"+"="+result1+ "litre"+"   ราคา   "+gas91+"บาท"+"\n";
            vatmsg = "Gasoline PTT Tax Invoice Gasohol91 "+"\n"+result1+"litre"+"  ราคา  "+gas91+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gas91+" Bath "+"\n";
            txtresult1.setText(String.valueOf(msg1));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
                //JOptionPane.showMessageDialog(null, "กรุณาเลือกปั๊มน้ำมัน");
        }
        
        if (sign.equals("Benzin91") && sign1.equals("PTT")){
            ben91 = Float.parseFloat(txtbenzin.getText());
            result2 = (float) (ben91 / 41.54);
            Amount = (float) (ben91 / 1.07);
            vat = (float) (Amount*7)/100;
            
            msg2 = "Gasoline PTT (Receipt) Benzin91 "+"\n"+"="+result2+"litre"+"  ราคา  "+ben91+"บาท"+"\n";
            vatmsg = "Gasoline PTT Tax Invoice Benzin91 "+"\n"+result2+"litre"+"  ราคา  "+ben91+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+ben91+" Bath "+"\n";
            txtresult1.setText(String.valueOf(msg2));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
                //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ :");
        }
        
        if (sign.equals("Gasohol95") && sign1.equals("BCP")) {
            gas95 = Float.parseFloat(txtbenzin.getText());
            result = (float) (gas95 / 37.74);
            Amount = (float) (gas95/1.07);
            vat = (float) (Amount*7)/100;
            
            msg = "Gasoline BCP บางจาก (Receipt) Gasohol95  "+"\n"+"="+result+"litre"+"  ราคา  "+gas95+"บาท"+"\n";
            vatmsg = "Gasoline BCP ยางจาก Tax Invoice Gasohol 95 "+"\n"+result+"litre"+"  ราคา  "+gas95+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gas95+" Bath "+"\n";
                    
            txtresult1.setText(String.valueOf(msg));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
            //JOptionPane.showMessageDialog(null, "กรุณาเลือกปั๊มPTT :");
        }
          
        if (sign.equals("Gasohol91") && sign1.equals("BCP")){
            gas91 = Float.parseFloat(txtbenzin.getText());
            result1 = (float) (gas91 / 35.24);
            Amount = (float) (gas91 / 1.07);
            vat = (float) (Amount*7)/100;
            
            msg1 = "Gasoline BCP บางจาก (Receipt) Gasohol91  "+"\n"+"="+result1+ "litre"+"   ราคา   "+gas91+"บาท"+"\n";
            vatmsg = "Gasoline BCP บางจาก Tax Invoice Gasohol91 "+"\n"+result1+"litre"+"  ราคา  "+gas91+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gas91+" Bath "+"\n";
            txtresult1.setText(String.valueOf(msg1));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
                //JOptionPane.showMessageDialog(null, "กรุณาเลือกปั๊มน้ำมัน");
        }
        
        if (sign.equals("Benzin91") && sign1.equals("BCP")){
            ben91 = Float.parseFloat(txtbenzin.getText());
            result2 = (float) (ben91 / 42.64);
            Amount = (float) (ben91 / 1.07);
            vat = (float) (Amount*7)/100;
            
            msg2 = "Gasoline BCP บางจาก (Receipt) Benzin91 "+"\n"+"="+result2+"litre"+"  ราคา  "+ben91+"บาท"+"\n";
            vatmsg = "Gasoline BCP บางจาก Tax Invoice Benzin91 "+"\n"+result2+"litre"+"  ราคา  "+ben91+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+ben91+" Bath "+"\n";
            txtresult1.setText(String.valueOf(msg2));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
                //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ :");
        }
        
        if (sign.equals("Gasohol95") && sign1.equals("Shell")) {
            gas95 = Float.parseFloat(txtbenzin.getText());
            result = (float) (gas95 / 37.34);
            Amount = (float) (gas95/1.07);
            vat = (float) (Amount*7)/100;
            
            msg = "Gasoline Shell (Receipt) Gasohol95  "+"\n"+"="+result+"litre"+"  ราคา  "+gas95+"บาท"+"\n";
            vatmsg = "Gasoline Shell Tax Invoice Gasohol 95 "+"\n"+result+"litre"+"  ราคา  "+gas95+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gas95+" Bath "+"\n";
                    
            txtresult1.setText(String.valueOf(msg));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
            //JOptionPane.showMessageDialog(null, "กรุณาเลือกปั๊มPTT :");
        }
          
        if (sign.equals("Gasohol91") && sign1.equals("Shell")){
            gas91 = Float.parseFloat(txtbenzin.getText());
            result1 = (float) (gas91 / 35.04);
            Amount = (float) (gas91 / 1.07);
            vat = (float) (Amount*7)/100;
            
            msg1 = "Gasoline Shell (Receipt) Gasohol91  "+"\n"+"="+result1+ "litre"+"   ราคา   "+gas91+"บาท"+"\n";
            vatmsg = "Gasoline Shell Tax Invoice Gasohol91 "+"\n"+result1+"litre"+"  ราคา  "+gas91+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gas91+" Bath "+"\n";
            txtresult1.setText(String.valueOf(msg1));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
                //JOptionPane.showMessageDialog(null, "กรุณาเลือกปั๊มน้ำมัน");
        }
        
        if (sign.equals("Benzin91") && sign1.equals("Shell")){
            ben91 = Float.parseFloat(txtbenzin.getText());
            result2 = (float) (ben91 / 41.84);
            Amount = (float) (ben91 / 1.07);
            vat = (float) (Amount*7)/100;
            
            msg2 = "Gasoline Shell (Receipt) Benzin91 "+"\n"+"="+result2+"litre"+"  ราคา  "+ben91+"บาท"+"\n";
            vatmsg = "Gasoline Shell Tax Invoice Benzin91 "+"\n"+result2+"litre"+"  ราคา  "+ben91+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+ben91+" Bath "+"\n";
            txtresult1.setText(String.valueOf(msg2));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
                //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ :");
        }
        
        if (sign.equals("Gasohol95") && sign1.equals("Esso")) {
            gas95 = Float.parseFloat(txtbenzin.getText());
            result = (float) (gas95 / 37.03);
            Amount = (float) (gas95/1.07);
            vat = (float) (Amount*7)/100;
            
            msg = "Gasoline Esso (Receipt) Gasohol95  "+"\n"+"="+result+"litre"+"  ราคา  "+gas95+"บาท"+"\n";
            vatmsg = "Gasoline Esso Tax Invoice Gasohol 95 "+"\n"+result+"litre"+"  ราคา  "+gas95+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gas95+" Bath "+"\n";
                    
            txtresult1.setText(String.valueOf(msg));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
            //JOptionPane.showMessageDialog(null, "กรุณาเลือกปั๊มPTT :");
        }
          
        if (sign.equals("Gasohol91") && sign1.equals("Esso")){
            gas91 = Float.parseFloat(txtbenzin.getText());
            result1 = (float) (gas91 / 35.34);
            Amount = (float) (gas91 / 1.07);
            vat = (float) (Amount*7)/100;
            
            msg1 = "Gasoline Esso (Receipt) Gasohol91  "+"\n"+"="+result1+ "litre"+"   ราคา   "+gas91+"บาท"+"\n";
            vatmsg = "Gasoline Esso Tax Invoice Gasohol91 "+"\n"+result1+"litre"+"  ราคา  "+gas91+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gas91+" Bath "+"\n";
            txtresult1.setText(String.valueOf(msg1));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
                //JOptionPane.showMessageDialog(null, "กรุณาเลือกปั๊มน้ำมัน");
        }
        
        if (sign.equals("Benzin91") && sign1.equals("Esso")){
            ben91 = Float.parseFloat(txtbenzin.getText());
            result2 = (float) (ben91 / 41.55);
            Amount = (float) (ben91 / 1.07);
            vat = (float) (Amount*7)/100;
            
            msg2 = "Gasoline Esso (Receipt) Benzin91 "+"\n"+"="+result2+"litre"+"  ราคา  "+ben91+"บาท"+"\n";
            vatmsg = "Gasoline Esso Tax Invoice Benzin91 "+"\n"+result2+"litre"+"  ราคา  "+ben91+"บาท"+"\n"+
                     "Amount : "+Amount+"\n"
                     +"Vat 7% : "+vat+"( Amount 7% )"+"\n"
                    +"Total Amount :"+ben91+" Bath "+"\n";
            txtresult1.setText(String.valueOf(msg2));
            txtresult2.setText(String.valueOf(vatmsg));
        }else{
                //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ :");
        }
        
        
        
        
    }//GEN-LAST:event_btnbenzinActionPerformed

    private void signgasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signgasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signgasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtbenzin.setText("");
        txtdiesel.setText("");
        txtresult2.setText("");
        txtresult1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbenzinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbenzinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbenzinActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Do you want to exit");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btndieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndieselActionPerformed
        // TODO add your handling code here:
        String dsg, dsg1, vatmsg1,vatmsg2 = null;
        float gasb7 = 0, gaspre = 0, resultd1 = 0, resultd2 = 0;
        float Amountd1 = 0,vatd1 = 0;
        
        String sign2 = (String) signdiesel.getSelectedItem();
        String sign3 = (String) cbxgas2.getSelectedItem();
 
        if (sign2.equals("DieselB7") && sign3.equals("PTT")) {
            gasb7 = Float.parseFloat(txtdiesel.getText());
            resultd1 = (float) (gasb7 / 29.34);
            Amountd1 = (float) (gasb7/1.07);
            vatd1 = (float) (Amountd1*7)/100;
            
            dsg = "Gasoline PTT (Receipt) DieselB7  "+"\n"+"="+resultd1+"litre"+"  ราคา  "+gasb7+"บาท"+"\n";
            vatmsg1 = "Gasoline PTT Tax Invoice DieselB7  "+"\n"+resultd1+"litre"+"  ราคา  "+gasb7+"บาท"+"\n"+
                     "Amount : "+Amountd1+"\n"
                     +"Vat 7% : "+vatd1+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gasb7+" Bath "+"\n";
                    
            txtresult1.setText(String.valueOf(dsg));
            txtresult2.setText(String.valueOf(vatmsg1));
            JOptionPane.showMessageDialog(this, "ขอบคุณที่ใช้บริการ PTT กรุณากด OK รับใบเสร็จ");
        }else{
            
        }
          
        if (sign2.equals("DieselPremium") && sign3.equals("PTT")){
            gaspre = Float.parseFloat(txtdiesel.getText());
            resultd2 = (float) (gaspre / 30.34);
            Amountd1 = (float) (gaspre / 1.07);
            vatd1 = (float) (Amountd1*7)/100;
            
            dsg1 = "Gasoline PTT Premium (Receipt) DieselPremium  "+"\n"+"="+resultd2+ "litre"+"   ราคา   "+gaspre+"บาท"+"\n";
            vatmsg2 = "Gasoline PTT Premium Tax Invoice DieselPremium "+"\n"+resultd2+"litre"+"  ราคา  "+gaspre+"บาท"+"\n"+
                     "Amount : "+Amountd1+"\n"
                     +"Vat 7% : "+vatd1+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gaspre+" Bath "+"\n";
            txtresult1.setText(String.valueOf(dsg1));
            txtresult2.setText(String.valueOf(vatmsg2));
            JOptionPane.showMessageDialog(this, "ขอบคุณที่ใช้บริการ PTT Premium กรุณากด OK รับใบเสร็จ");
        }else{
                //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ PTT กรุณากด OK รับใบเสร็จ");
        }
        
        if (sign2.equals("DieselB7") && sign3.equals("BCP")) {
            gasb7 = Float.parseFloat(txtdiesel.getText());
            resultd1 = (float) (gasb7 / 28.99);
            Amountd1 = (float) (gasb7/1.07);
            vatd1 = (float) (Amountd1*7)/100;
            
            dsg = "Gasoline BCP (Receipt) DieselB7  "+"\n"+"="+resultd1+"litre"+"  ราคา  "+gasb7+"บาท"+"\n";
            vatmsg1 = "Gasoline BCP Tax Invoice DieselB7  "+"\n"+resultd1+"litre"+"  ราคา  "+gasb7+"บาท"+"\n"+
                     "Amount : "+Amountd1+"\n"
                     +"Vat 7% : "+vatd1+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gasb7+" Bath "+"\n";
                    
            txtresult1.setText(String.valueOf(dsg));
            txtresult2.setText(String.valueOf(vatmsg1));
            JOptionPane.showMessageDialog(this, "ขอบคุณที่ใช้บริการ บางจาก กรุณากด OK รับใบเสร็จ");
        }else{
            //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ บางจาก กรุณากด OK รับใบเสร็จ");
        }
          
        if (sign2.equals("DieselPremium") && sign3.equals("BCP")){
            gaspre = Float.parseFloat(txtdiesel.getText());
            resultd2 = (float) (gaspre / 30.29);
            Amountd1 = (float) (gaspre / 1.07);
            vatd1 = (float) (Amountd1*7)/100;
            
            dsg1 = "Gasoline BCP Premium (Receipt) DieselPremium  "+"\n"+"="+resultd2+ "litre"+"   ราคา   "+gaspre+"บาท"+"\n";
            vatmsg2 = "Gasoline BCP Premium Tax Invoice DieselPremium "+"\n"+resultd2+"litre"+"  ราคา  "+gaspre+"บาท"+"\n"+
                     "Amount : "+Amountd1+"\n"
                     +"Vat 7% : "+vatd1+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gaspre+" Bath "+"\n";
            txtresult1.setText(String.valueOf(dsg1));
            txtresult2.setText(String.valueOf(vatmsg2));
            JOptionPane.showMessageDialog(this, "ขอบคุณที่ใช้บริการ บางจาก Premium กรุณากด OK รับใบเสร็จ");
        }else{
                //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ บางจาก กรุณากด OK รับใบเสร็จ");
        }
        
        if (sign2.equals("DieselB7") && sign3.equals("Shell")) {
            gasb7 = Float.parseFloat(txtdiesel.getText());
            resultd1 = (float) (gasb7 / 28.20);
            Amountd1 = (float) (gasb7/1.07);
            vatd1 = (float) (Amountd1*7)/100;
            
            dsg = "Gasoline Shell (Receipt) DieselB7  "+"\n"+"="+resultd1+"litre"+"  ราคา  "+gasb7+"บาท"+"\n";
            vatmsg1 = "Gasoline Shell Tax Invoice DieselB7  "+"\n"+resultd1+"litre"+"  ราคา  "+gasb7+"บาท"+"\n"+
                     "Amount : "+Amountd1+"\n"
                     +"Vat 7% : "+vatd1+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gasb7+" Bath "+"\n";
                    
            txtresult1.setText(String.valueOf(dsg));
            txtresult2.setText(String.valueOf(vatmsg1));
            JOptionPane.showMessageDialog(this, "ขอบคุณที่ใช้บริการ Shell กรุณากด OK รับใบเสร็จ");
        }else{
            //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ บางจาก กรุณากด OK รับใบเสร็จ");
        }
          
        if (sign2.equals("DieselPremium") && sign3.equals("Shell")){
            gaspre = Float.parseFloat(txtdiesel.getText());
            resultd2 = (float) (gaspre / 29.89);
            Amountd1 = (float) (gaspre / 1.07);
            vatd1 = (float) (Amountd1*7)/100;
            
            dsg1 = "Gasoline Shell (Receipt) DieselPremium  "+"\n"+"="+resultd2+ "litre"+"   ราคา   "+gaspre+"บาท"+"\n";
            vatmsg2 = "Gasoline Shell Premium Tax Invoice DieselPremium "+"\n"+resultd2+"litre"+"  ราคา  "+gaspre+"บาท"+"\n"+
                     "Amount : "+Amountd1+"\n"
                     +"Vat 7% : "+vatd1+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gaspre+" Bath "+"\n";
            txtresult1.setText(String.valueOf(dsg1));
            txtresult2.setText(String.valueOf(vatmsg2));
            JOptionPane.showMessageDialog(this, "ขอบคุณที่ใช้บริการ Shell Premium กรุณากด OK รับใบเสร็จ");
        }else{
                //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ บางจาก กรุณากด OK รับใบเสร็จ");
        }
        
        if (sign2.equals("DieselB7") && sign3.equals("Esso")) {
            gasb7 = Float.parseFloat(txtdiesel.getText());
            resultd1 = (float) (gasb7 / 29.10);
            Amountd1 = (float) (gasb7/1.07);
            vatd1 = (float) (Amountd1*7)/100;
            
            dsg = "Gasoline Esso (Receipt) DieselB7  "+"\n"+"="+resultd1+"litre"+"  ราคา  "+gasb7+"บาท"+"\n";
            vatmsg1 = "Gasoline Esso Tax Invoice DieselB7  "+"\n"+resultd1+"litre"+"  ราคา  "+gasb7+"บาท"+"\n"+
                     "Amount : "+Amountd1+"\n"
                     +"Vat 7% : "+vatd1+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gasb7+" Bath "+"\n";
                    
            txtresult1.setText(String.valueOf(dsg));
            txtresult2.setText(String.valueOf(vatmsg1));
            JOptionPane.showMessageDialog(this, "ขอบคุณที่ใช้บริการ Esso กรุณากด OK รับใบเสร็จ");
        }else{
            //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ บางจาก กรุณากด OK รับใบเสร็จ");
        }
          
        if (sign2.equals("DieselPremium") && sign3.equals("Esso")){
            gaspre = Float.parseFloat(txtdiesel.getText());
            resultd2 = (float) (gaspre / 30.29);
            Amountd1 = (float) (gaspre / 1.07);
            vatd1 = (float) (Amountd1*7)/100;
            
            dsg1 = "Gasoline Esso (Receipt) DieselPremium  "+"\n"+"="+resultd2+ "litre"+"   ราคา   "+gaspre+"บาท"+"\n";
            vatmsg2 = "Gasoline Esso premium Tax Invoice DieselPremium "+"\n"+resultd2+"litre"+"  ราคา  "+gaspre+"บาท"+"\n"+
                     "Amount : "+Amountd1+"\n"
                     +"Vat 7% : "+vatd1+"( Amount 7% )"+"\n"
                    +"Total Amount :"+gaspre+" Bath "+"\n";
            txtresult1.setText(String.valueOf(dsg1));
            txtresult2.setText(String.valueOf(vatmsg2));
            JOptionPane.showMessageDialog(this, "ขอบคุณที่ใช้บริการ Esso premium กรุณากด OK รับใบเสร็จ");
        }else{
                //JOptionPane.showMessageDialog(null, "ขอบคุณที่ใช้บริการ บางจาก กรุณากด OK รับใบเสร็จ");
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btndieselActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GasolineCalculationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GasolineCalculationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GasolineCalculationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GasolineCalculationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GasolineCalculationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnbenzin;
    private javax.swing.JButton btndiesel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxgas;
    private javax.swing.JComboBox<String> cbxgas2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> signdiesel;
    private javax.swing.JComboBox<String> signgas;
    private javax.swing.JTextField txtbenzin;
    private javax.swing.JTextField txtdiesel;
    private javax.swing.JTextArea txtresult1;
    private javax.swing.JTextArea txtresult2;
    // End of variables declaration//GEN-END:variables
}
