package miniproject;

import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class MainMenuGUI extends javax.swing.JFrame {

    
    Matrix frmMatrix;
    Gasoline frmGasoline;
    static String userType;

    /**
     * Creates new form MainMenuGUI
     * @param inpUserType
     */
    public MainMenuGUI(String inpUserType) {
        super();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpShow = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        menuMatrix = new javax.swing.JMenu();
        menuGasoline = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpShowLayout = new javax.swing.GroupLayout(dpShow);
        dpShow.setLayout(dpShowLayout);
        dpShowLayout.setHorizontalGroup(
            dpShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
        );
        dpShowLayout.setVerticalGroup(
            dpShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );

        jMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBarMouseClicked(evt);
            }
        });

        menuMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/matrix2.png"))); // NOI18N
        menuMatrix.setText("MatrixLength");
        menuMatrix.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        menuMatrix.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuMatrix.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuMatrix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMatrixMouseClicked(evt);
            }
        });
        menuMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatrixActionPerformed(evt);
            }
        });
        jMenuBar.add(menuMatrix);

        menuGasoline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/gasoline2.png"))); // NOI18N
        menuGasoline.setText("Gasoline");
        menuGasoline.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        menuGasoline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuGasoline.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuGasoline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGasolineMouseClicked(evt);
            }
        });
        jMenuBar.add(menuGasoline);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBarMouseClicked

    private void menuMatrixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMatrixMouseClicked
        // TODO add your handling code here:
        frmMatrix = new Matrix();
        this.dpShow.add(frmMatrix);
        frmMatrix.setVisible(true);
        frmMatrix.setSize(this.getSize());
    }//GEN-LAST:event_menuMatrixMouseClicked

    private void menuGasolineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGasolineMouseClicked
        // TODO add your handling code here:
        frmGasoline = new Gasoline();
        this.dpShow.add(frmGasoline);
        frmGasoline.setVisible(true);
        frmGasoline.setSize(this.getSize());
    }//GEN-LAST:event_menuGasolineMouseClicked

    private void menuMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatrixActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuMatrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI(userType).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpShow;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu menuGasoline;
    private javax.swing.JMenu menuMatrix;
    // End of variables declaration//GEN-END:variables
}
